version: '3.8'
services:
  APPNAME-app:
    image: IMAGETAG
    ports:
      - PORTNUM:PORTNUM2
    networks:
      - danai-net
    restart: always
    volumes:
      - danai-vol:/danaiid/peruri/logs
      - danai-vol:/danaiid/peruri/sharefolder
volumes:
  danai-vol:
    external: true
networks:
  danai-net:
    external: true
  